name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtwidgets'
        arch: 'win64_mingw81'
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Init QMake
      run: qmake .
    - name: Build 
      run: make
    - run: tree /F
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: Built executable (${{ matrix.os }})
        path: ./build/GeneratorOfGenerators.exe
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: Built executable (${{ matrix.os }})
        path: ./build/GeneratorOfGenerators
