name: Build
on: [push]
jobs:
  build-linux-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtwidgets'
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Init QMake
      run: qmake .
    - name: Build 
      run: mingw64-make.exe
